apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: experimento1
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: dlariosuniandes/ex1-api-gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: URL_MICRO
          value: http://load-balancer-micro.experimento1:8081
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
  labels:
    app: microservicio
  namespace: experimento1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
      - name: sidecar
        image: dlariosuniandes/ex1-sidecar:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        env:
        - name: URL_MICRO
          value: http://localhost:8001
      - name: micro
        image: dlariosuniandes/ex1-micro:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-api-gateway
  namespace: experimento1
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-micro
  namespace: experimento1
spec:
  selector:
    app: microservicio
  ports:
    - name: http
      port: 8081
      targetPort: 8002
  type: LoadBalancer